### ISSUE TITLE
Create new order

### ISSUE THREAD

**Issue by BradleyKirton** [armandvanderwalt/ice3x-api#1]
Hi Armand, I have written a python library for the ICE3X API and I am getting a weird response from the https://ice3x.com/api/v1/order/new/ resource.

When I post to this uri I get the following response.

```json
{"errors": "Please try again in few seconds", "response": false}
```

Do you receive the same response in your library?

**Comment by armandvanderwalt** [comment]
Hi Bradley,

No I haven’t received that one yet, most likely the cause is related to a rate limiter, I’m not sure what the ICE3X limits are right now, but I only call the API every 20 seconds and now more.

Regards

Sent from my iPhone

On 20 Mar 2018, at 18:11, Bradley Stuart Kirton <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Armand, I have written a python library for the ICE3X API and I am getting a weird response from the https://ice3x.com/api/v1/order/new/ resource.

When I post to this uri I get the following response.

{"errors": "Please try again in few seconds", "response": false}

Do you receive the same response in your library?

**Comment by BradleyKirton** [comment]
Awesome, thanks for the feedback. 

I must be missing something, I will read through your library again and see what I can find.
